### ISSUE TITLE
Mobile browsers zoom in when horizontal (CSS missing `text-size-adjust` property)

### ISSUE THREAD

**Issue by aaaxx** [rust-lang-nursery/mdBook#184]
The CSS is missing a pretty standard piece of code (e.g. it's used in Normalize.css and other templates) that prevents mobile browser from zooming in when turned horizontally:

```css
html {
    -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
}
```

![mobile browser example](https://cloud.githubusercontent.com/assets/6186480/20854243/62f3be98-b8f2-11e6-98f6-4a0ec0a0bf5c.png)

**Comment by azerupi** [comment]
I agree.
Although, instead of adding those fixes manually, I wonder if it wouldn't be better to use a normalization framework (`normalize.css`). They probably contain other fixes that we are missing.

There is a [version of normalize.css for stylus](https://github.com/bymathias/normalize.styl), it's just a matter of adding it to the npm dependencies, importing it in the main stylus files and checking that it didn't break anything.

**Comment by aaaxx** [comment]
Sounds good.

**Comment by mattico** [comment]
I believe this issue has been fixed, but feel free to reopen.

![image](https://user-images.githubusercontent.com/853158/43154830-49b34dce-8f3b-11e8-98cc-7bfcffe9b68d.png)

![image](https://user-images.githubusercontent.com/853158/43154844-5355a34a-8f3b-11e8-808a-82656ffab375.png)

**Comment by aaaxx** [comment]
Nope. Still happens. Seems that device emulation in browsers isn't really accurate. I'd post a screenshot, but, all of a sudden, my iPhone is refusing to take them while horizontal, for some reason.

Besides, the piece of code from the first post is what controls the behaviour, and it's still not in the codebase, so nothing has really changed regarding the issue.

I can't seem reopen the issue myself.

**Comment by aaaxx** [comment]
Managed to get a screenshot:

![portrait and landscape screenshots side by side; the landscape one shows larger text](https://user-images.githubusercontent.com/6186480/43173673-67726644-8fb6-11e8-9a1e-5504cf756063.png)

**Comment by mattico** [comment]
Interesting, it must be an iOS thing. Thanks for testing it! I'll get this fixed.
